# Site settings
title: Sports About Data
email: chrisdsheehan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site (mostly) about sports data and random other analyses using Python
  and probably some Excel. 
baseurl: "bad-data" # the subpath of your site, e.g. /blog/
url: 'chris-sheehan.github.io' # the base hostname & protocol for your site
url: "localhost:4000"
twitter_username: chrisdsheehan
github_username:  chris-sheehan

# Build settings
markdown: kramdown
